# Generated by Django 2.2.4 on 2019-09-10 09:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transform_sql', models.FileField(help_text='Transform SQL', upload_to='')),
                ('sync_db', models.FileField(blank=True, help_text='Sync SQLite database', null=True, upload_to='')),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('failed', 'failed'), ('success', 'success'), ('timeout', 'timeout')], default='in_progress', help_text='Current status of the activity', max_length=20)),
                ('triggered_by', models.CharField(choices=[('user', 'user'), ('schedule', 'schedule'), ('api', 'api')], default='user', help_text='Activity triggered by', max_length=20)),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='API request data', null=True)),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='API response data', null=True)),
                ('error_msg', models.TextField(blank=True, help_text='Error message for user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
        ),
    ]
