# Generated by Django 2.2.4 on 2019-09-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sync_db',
            field=models.FileField(blank=True, help_text='SQLite database', null=True, upload_to=''),
        ),
    ]
