# Generated by Django 2.2.4 on 2019-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_activity', '0003_auto_20191003_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='transform_sql',
            field=models.TextField(blank=True, help_text='Transform SQL', null=True),
        ),
    ]
