# Generated by Django 2.2.4 on 2019-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_activity', '0004_activity_transform_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='request_data',
            field=models.TextField(blank=True, help_text='Request data for Xero invoice creation', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='response_data',
            field=models.TextField(blank=True, help_text='Response data for Xero invoice creation', null=True),
        ),
    ]
