# Generated by Django 2.2.4 on 2019-10-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_activity', '0005_auto_20191003_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='request_data',
            field=models.TextField(blank=True, help_text='Request data', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='response_data',
            field=models.TextField(blank=True, help_text='Response data', null=True),
        ),
    ]
