# Generated by Django 3.0 on 2019-12-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191227_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='task',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task_id',
            field=models.CharField(default='default', help_text='Django Q task id', max_length=64),
            preserve_default=False,
        ),
    ]
