# Generated by Django 2.2.4 on 2020-01-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20191227_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='status',
            field=models.CharField(default='default', help_text='Task status', max_length=64),
            preserve_default=False,
        ),
    ]
