# Generated by Django 2.2.8 on 2020-01-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20200115_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='expense_group',
            field=models.ForeignKey(blank=True, help_text='FK to ExpenseGroup', null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.ExpenseGroup'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(help_text='FK to Django Q Task', on_delete=django.db.models.deletion.CASCADE, to='django_q.Task'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='workspace',
            field=models.ForeignKey(help_text='FK to Workspace', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace'),
        ),
    ]
