# Generated by Django 3.0 on 2019-12-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xero_workspace', '0007_auto_20191226_1040'),
        ('django_q', '0009_auto_20171009_0915'),
        ('expense', '0007_auto_20191226_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(help_text='Level', max_length=64)),
                ('detail', models.TextField(help_text='Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('expense_group', models.ForeignKey(blank=True, help_text='FK to ExpenseGroup', null=True, on_delete=django.db.models.deletion.PROTECT, to='expense.ExpenseGroup')),
                ('invoice', models.ForeignKey(blank=True, help_text='FK to Invoice', null=True, on_delete=django.db.models.deletion.PROTECT, to='xero_workspace.Invoice')),
                ('task', models.ForeignKey(help_text='FK to Task', on_delete=django.db.models.deletion.PROTECT, to='django_q.Task')),
                ('workspace', models.ForeignKey(help_text='FK to Workspace', on_delete=django.db.models.deletion.PROTECT, to='xero_workspace.Workspace')),
            ],
        ),
    ]
