# Generated by Django 2.2.8 on 2020-03-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fyle_expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(help_text='Fyle job reference', max_length=255, null=True)),
                ('type', models.CharField(help_text='Task type', max_length=64)),
                ('status', models.CharField(blank=True, help_text='Task status', max_length=64, null=True)),
                ('detail', models.TextField(blank=True, help_text='Task details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('expense_group', models.ForeignKey(blank=True, help_text='FK to ExpenseGroup', null=True, on_delete=django.db.models.deletion.CASCADE, to='fyle_expense.ExpenseGroup')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
