# Generated by Django 2.2.8 on 2020-01-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_q', '0009_auto_20171009_0915'),
        ('task_log', '0001_initial'),
        ('xero_workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='FK to Invoice', null=True, on_delete=django.db.models.deletion.PROTECT, to='xero_workspace.Invoice'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(help_text='FK to Django Q Task', on_delete=django.db.models.deletion.CASCADE, to='django_q.Task'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='workspace',
            field=models.ForeignKey(help_text='FK to Workspace', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace'),
        ),
    ]
