# Generated by Django 3.0 on 2019-12-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='detail',
            field=models.TextField(blank=True, help_text='Detail', null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='level',
            field=models.CharField(blank=True, help_text='Level', max_length=64, null=True),
        ),
    ]
