# Generated by Django 2.2.4 on 2020-01-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0009_auto_20171009_0915'),
        ('task', '0004_tasklog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task_id',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(default=1, help_text='Django Q task id', on_delete=django.db.models.deletion.PROTECT, to='django_q.Task'),
            preserve_default=False,
        ),
    ]
