# Generated by Django 2.2.8 on 2020-01-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20200115_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklog',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
