# Generated by Django 3.0 on 2019-12-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroup',
            name='expenses',
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='expenses',
            field=models.ManyToManyField(help_text='Expenses under this Expense Group', to='expense.Expense'),
        ),
    ]
