# Generated by Django 2.2.8 on 2020-01-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_expense', '0002_auto_20200118_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='status',
            field=models.CharField(default='Complete', help_text='Status', max_length=10),
            preserve_default=False,
        ),
    ]
