# Generated by Django 3.0 on 2019-12-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20191217_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.CharField(help_text='Project', max_length=64, null=True),
        ),
    ]
