# Generated by Django 3.0 on 2019-12-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20191217_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, help_text='Fyle Expense Category', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.CharField(blank=True, help_text='Project', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='sub_category',
            field=models.CharField(blank=True, help_text='Fyle Expense Sub-Category', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, help_text='Vendor', max_length=64, null=True),
        ),
    ]
