# Generated by Django 3.0 on 2019-12-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0003_invoice_invoicelineitem'),
        ('expense', '0005_auto_20191217_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice_lineitem',
            field=models.ForeignKey(blank=True, help_text='FK to Invoice Lineitem', null=True, on_delete=django.db.models.deletion.PROTECT, to='xero_workspace.InvoiceLineItem'),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='FK to Invoice', null=True, on_delete=django.db.models.deletion.PROTECT, to='xero_workspace.Invoice'),
        ),
    ]
