# Generated by Django 3.0 on 2019-12-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0007_auto_20191226_1040'),
        ('expense', '0006_auto_20191220_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='invoice_lineitem',
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_line_item',
            field=models.ForeignKey(blank=True, help_text='FK to InvoiceLineItem', null=True, on_delete=django.db.models.deletion.PROTECT, to='xero_workspace.InvoiceLineItem'),
        ),
    ]
