# Generated by Django 2.2.8 on 2020-01-16 13:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_auto_20200115_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Description'),
        ),
    ]
