# Generated by Django 2.2.4 on 2019-10-18 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_q', '0009_auto_20171009_0915'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fyle_connect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of this workspace', max_length=20)),
                ('transform_sql', models.TextField(blank=True, help_text='Transform SQL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('user', models.ManyToManyField(help_text='Users belonging to this workspace', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XeroCredential',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('private_key', models.TextField(help_text='Xero Application Private Key')),
                ('consumer_key', models.CharField(help_text='Xero Consumer key', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.OneToOneField(help_text='Workspace', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('schedule', models.OneToOneField(help_text='FK to Schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.Schedule')),
                ('workspace', models.OneToOneField(help_text='FK to Workspace', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FyleCredential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('fyle_auth', models.OneToOneField(help_text='FK to Fyle Auth', on_delete=django.db.models.deletion.CASCADE, to='fyle_connect.FyleAuth')),
                ('workspace', models.OneToOneField(help_text='FK to Workspace', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_email', models.EmailField(help_text='Email id of the Fyle employee', max_length=255)),
                ('contact_name', models.CharField(help_text='Name of the Xero contact', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.ForeignKey(help_text='Workspace this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='Fyle Expense Category', max_length=64)),
                ('sub_category', models.CharField(help_text='Fyle Expense Sub-Category', max_length=64, null=True)),
                ('account_code', models.IntegerField(blank=True, help_text='Xero Account code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.ForeignKey(help_text='Workspace this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transform_sql', models.TextField(blank=True, help_text='Transform SQL', null=True)),
                ('sync_db_file_id', models.CharField(blank=True, help_text='SQLite database file Id', max_length=32, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('failed', 'failed'), ('success', 'success'), ('timeout', 'timeout')], default='in_progress', help_text='Current status of the activity', max_length=20)),
                ('triggered_by', models.CharField(choices=[('user', 'user'), ('schedule', 'schedule'), ('api', 'api')], default='user', help_text='Activity triggered by', max_length=20)),
                ('request_data', models.TextField(blank=True, help_text='Request data', null=True)),
                ('response_data', models.TextField(blank=True, help_text='Response data', null=True)),
                ('error_msg', models.TextField(blank=True, help_text='Error message for user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.OneToOneField(help_text='FK to Workspace', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace')),
            ],
        ),
    ]
