# Generated by Django 2.2.8 on 2020-03-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceschedule',
            name='schedule',
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Schedule enabled'),
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='fyle_job_id',
            field=models.CharField(help_text='Fyle job ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='interval_hours',
            field=models.IntegerField(help_text='Interval in hours', null=True),
        ),
        migrations.AddField(
            model_name='workspaceschedule',
            name='start_datetime',
            field=models.DateTimeField(help_text='Datetime for start of schedule', null=True),
        ),
    ]
