# Generated by Django 2.2.8 on 2020-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='account_code',
            field=models.CharField(blank=True, help_text='Xero Account code', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='account_code',
            field=models.CharField(help_text='Account Code', max_length=32),
        ),
    ]
