# Generated by Django 2.2.4 on 2019-09-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceactivity',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='FK to Activity', null=True, on_delete=django.db.models.deletion.CASCADE, to='sync_activity.Activity'),
        ),
    ]
