# Generated by Django 3.0 on 2019-12-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(help_text='Fyle Project Name', max_length=64)),
                ('tracking_category_name', models.CharField(help_text='Xero Tracking Category Name', max_length=64)),
                ('tracking_category_option', models.CharField(help_text='Xero Tracking Category Option', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.ForeignKey(help_text='Workspace this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace')),
            ],
        ),
    ]
