# Generated by Django 2.2.4 on 2019-09-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0002_auto_20190912_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerocredential',
            name='workspace',
            field=models.OneToOneField(help_text='Workspace', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace'),
        ),
    ]
