# Generated by Django 3.0 on 2019-12-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0002_projectmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Invoice number', max_length=64)),
                ('invoice_id', models.CharField(help_text='Invoice id', max_length=64)),
                ('contact_name', models.CharField(help_text='Contact Name', max_length=64)),
                ('date', models.DateTimeField(help_text='Invoice created date')),
                ('due_date', models.DateTimeField(help_text='Invoice due date')),
                ('description', models.CharField(help_text='Description', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_code', models.IntegerField(help_text='Account Code')),
                ('account_name', models.CharField(help_text='Account name', max_length=64)),
                ('description', models.CharField(help_text='Description', max_length=64)),
                ('amount', models.FloatField(help_text='Lineitem amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('invoice', models.ForeignKey(help_text='FK to Invoice', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Invoice')),
            ],
        ),
    ]
