# Generated by Django 2.2.4 on 2019-09-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0003_auto_20190917_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerocredential',
            name='file_id',
            field=models.CharField(default='', help_text='File upload id', max_length=32),
            preserve_default=False,
        ),
    ]
