# Generated by Django 3.0 on 2019-12-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0003_invoice_invoicelineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(blank=True, help_text='Invoice id', max_length=64, null=True),
        ),
    ]
