# Generated by Django 3.0 on 2019-12-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0004_auto_20191223_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='tracking_category_name',
            field=models.CharField(blank=True, help_text='Tracking Category Name', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='tracking_category_option',
            field=models.CharField(blank=True, help_text='Tracking Category Option', max_length=64, null=True),
        ),
    ]
