# Generated by Django 2.2.4 on 2019-09-20 09:57

import apps.xero_workspace.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0005_remove_xerocredential_pem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='category_account',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.xero_workspace.models.default_for_json_field, help_text='Fyle Category to Xero Account mapping'),
        ),
    ]
