# Generated by Django 3.0 on 2019-12-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0005_auto_20191224_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Invoice due date', null=True),
        ),
    ]
