# Generated by Django 2.2.4 on 2019-09-20 10:01

import apps.xero_workspace.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0006_auto_20190920_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='employee_contact',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.xero_workspace.models.default_for_json_field, help_text='Fyle Employee email to Xero Contact email mapping'),
        ),
    ]
