# Generated by Django 3.0 on 2019-12-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0006_auto_20191226_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='amount',
            field=models.FloatField(help_text='Invoice line item amount'),
        ),
    ]
