# Generated by Django 3.0 on 2019-12-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0007_auto_20191226_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(help_text='FK to Invoice', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line_items', to='xero_workspace.Invoice'),
        ),
    ]
