# Generated by Django 2.2.4 on 2020-01-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0008_auto_20191230_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
