# Generated by Django 2.2.4 on 2019-10-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0008_auto_20190930_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='category_account',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='employee_contact',
        ),
        migrations.CreateModel(
            name='EmployeeMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_email', models.EmailField(help_text='Email id of the Fyle employee', max_length=255)),
                ('contact_name', models.CharField(help_text='Name of the Xero contact', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.ForeignKey(help_text='Workspace this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='Fyle Expense Category', max_length=64)),
                ('sub_category', models.CharField(help_text='Fyle Expense Sub-Category', max_length=64)),
                ('account_code', models.IntegerField(blank=True, help_text='Xero Account code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('workspace', models.ForeignKey(help_text='Workspace this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace')),
            ],
        ),
    ]
