# Generated by Django 2.2.4 on 2019-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0009_auto_20191002_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='sub_category',
            field=models.CharField(help_text='Fyle Expense Sub-Category', max_length=64, null=True),
        ),
    ]
