# Generated by Django 2.2.8 on 2020-01-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0010_auto_20200109_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymapping',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employeemapping',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectmapping',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='valid',
            field=models.BooleanField(default=False, help_text='Indicates if this mapping is valid'),
        ),
        migrations.AddField(
            model_name='employeemapping',
            name='valid',
            field=models.BooleanField(default=False, help_text='Indicates if this mapping is valid'),
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='valid',
            field=models.BooleanField(default=False, help_text='Indicates if this mapping is valid'),
        ),
    ]
