# Generated by Django 2.2.8 on 2020-01-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0011_auto_20200115_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymapping',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='employeemapping',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='projectmapping',
            name='valid',
        ),
        migrations.AddField(
            model_name='categorymapping',
            name='invalid',
            field=models.BooleanField(default=False, help_text='Indicates if this mapping is invalid'),
        ),
        migrations.AddField(
            model_name='employeemapping',
            name='invalid',
            field=models.BooleanField(default=False, help_text='Indicates if this mapping is invalid'),
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='invalid',
            field=models.BooleanField(default=False, help_text='Indicates if this mapping is invalid'),
        ),
    ]
