# Generated by Django 2.2.4 on 2019-10-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0011_auto_20191003_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceschedule',
            name='schedule',
            field=models.OneToOneField(help_text='FK to Schedule', on_delete=django.db.models.deletion.CASCADE, to='django_q.Schedule'),
        ),
    ]
