# Generated by Django 2.2.4 on 2019-10-11 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0012_auto_20191007_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceschedule',
            name='schedule',
            field=models.OneToOneField(help_text='FK to Schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.Schedule'),
        ),
    ]
