# Generated by Django 2.2.8 on 2020-01-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0012_auto_20200115_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='transform_sql',
        ),
    ]
