# Generated by Django 2.2.8 on 2020-01-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero_workspace', '0013_remove_workspace_transform_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymapping',
            name='sub_category',
            field=models.CharField(default='Unspecified', help_text='Fyle Expense Sub-Category', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeemapping',
            name='employee_email',
            field=models.EmailField(help_text='Email id of the Fyle employee', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='project_name',
            field=models.CharField(help_text='Fyle Project Name', max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='categorymapping',
            unique_together={('category', 'sub_category')},
        ),
    ]
