# Generated by Django 3.0 on 2019-12-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xero_workspace', '0002_projectmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_email', models.EmailField(help_text='Email id of the Fyle employee', max_length=255)),
                ('category', models.CharField(help_text='Fyle Expense Category', max_length=64)),
                ('sub_category', models.CharField(help_text='Fyle Expense Sub-Category', max_length=64, null=True)),
                ('purpose', models.CharField(help_text='Purpose', max_length=64)),
                ('expense_id', models.CharField(help_text='Expense ID', max_length=64, unique=True)),
                ('expense_number', models.CharField(help_text='Expense Number', max_length=64, unique=True)),
                ('amount', models.FloatField(help_text='Amount')),
                ('settlement_id', models.CharField(help_text='Settlement ID', max_length=64)),
                ('report_id', models.CharField(help_text='Report ID', max_length=64)),
                ('project', models.CharField(help_text='Project', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at')),
                ('expenses', models.ForeignKey(help_text='Expenses under this Expense Group', on_delete=django.db.models.deletion.CASCADE, to='expense.Expense')),
                ('workspace', models.ForeignKey(help_text='To which workspace this expense group belongs to', on_delete=django.db.models.deletion.PROTECT, to='xero_workspace.Workspace')),
            ],
        ),
    ]
