# Generated by Django 3.0 on 2019-12-17 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20191216_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Expense created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursable',
            field=models.BooleanField(default=True, help_text='Expense reimbursable or not'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='spent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Expense spent at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='state',
            field=models.CharField(default='PAID', help_text='Expense state', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(default='None', help_text='Vendor', max_length=64),
            preserve_default=False,
        ),
    ]
