# Generated by Django 2.2.8 on 2020-01-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_auto_20191226_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expensegroup',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
