# Generated by Django 2.2.8 on 2020-01-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_auto_20200116_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='workspace',
            field=models.ForeignKey(help_text='To which workspace this expense group belongs to', on_delete=django.db.models.deletion.CASCADE, to='xero_workspace.Workspace'),
        ),
    ]
